webtalk_init -webtalk_dir C:/Users/82106/Desktop/2021/Fall_Semester/CD/LAB/Lab08/Lab08_DMA/Lab08_DMA.sim/sim_1/behav/xsim/xsim.dir/cpu_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov 30 16:39:23 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a4d2768b-5374-4029-bbe9-8c3aa7574c7c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ecf0d2b372104786a574719fb5cafd7c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "145" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "234850 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.12_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "10392_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2110112535 -regid "" -xml C:/Users/82106/Desktop/2021/Fall_Semester/CD/LAB/Lab08/Lab08_DMA/Lab08_DMA.sim/sim_1/behav/xsim/xsim.dir/cpu_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/82106/Desktop/2021/Fall_Semester/CD/LAB/Lab08/Lab08_DMA/Lab08_DMA.sim/sim_1/behav/xsim/xsim.dir/cpu_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/82106/Desktop/2021/Fall_Semester/CD/LAB/Lab08/Lab08_DMA/Lab08_DMA.sim/sim_1/behav/xsim/xsim.dir/cpu_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
